### ISSUE TITLE
Error: got error in command merge with option --merge-ref

### ISSUE THREAD

**Issue by danghai** [RH-FMK/skt#318]
I got error in command merge with option `--merge-ref`. I think I put wrong url: 
```
git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git
```
My command: 
```
skt --rc skt-rc --state --workdir skt-workdir -vv \
merge --baserepo git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git \
--ref a870a02cc963de35452bbed932560ed69725c4f2 \
--merge-ref 'git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git' 
```

My error:
```
Traceback (most recent call last):
  File "/usr/bin/skt", line 11, in <module>
    load_entry_point('skt', 'console_scripts', 'skt')()
  File "/home/danghai/skt/skt/executable.py", line 1028, in main
    args.func(cfg)
  File "/home/danghai/skt/skt/executable.py", line 168, in wrapper
    func(cfg)
  File "/home/danghai/skt/skt/executable.py", line 215, in cmd_merge
    (retcode, bhead) = ktree.merge_git_ref(*mb)
  File "/home/danghai/skt/skt/kerneltree.py", line 277, in merge_git_ref
    stderr=subprocess.PIPE)
  File "/home/danghai/skt/skt/kerneltree.py", line 110, in __git_cmd
    **kwargs)
  File "/home/danghai/skt/skt/kerneltree.py", line 93, in __git_cmd_call
    **kwargs
TypeError: check_output() got multiple values for keyword argument 'stderr'
```

**Comment by veruu** [comment]
Can you post the full verbose log as well so we have more information?

**Comment by danghai** [comment]
Yeah sure:
```
2018-08-07 09:47:52,729    DEBUG   executing: git --work-tree /home/danghai/skt/skt-workdir --git-dir /home/danghai/skt/skt-workdir/.git -c user.name=skt -c user.email=skt init
2018-08-07 09:47:52,738    DEBUG   executing: git --work-tree /home/danghai/skt/skt-workdir --git-dir /home/danghai/skt/skt-workdir/.git -c user.name=skt -c user.email=skt remote
2018-08-07 09:47:52,744    DEBUG   Setting URL for remote 'origin': git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git
2018-08-07 09:47:52,744    DEBUG   executing: git --work-tree /home/danghai/skt/skt-workdir --git-dir /home/danghai/skt/skt-workdir/.git -c user.name=skt -c user.email=skt remote set-url origin git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git
2018-08-07 09:47:52,748     INFO   base repo url: git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git
2018-08-07 09:47:52,748     INFO   base ref: a870a02cc963de35452bbed932560ed69725c4f2
2018-08-07 09:47:52,748     INFO   work dir: /home/danghai/skt/skt-workdir
2018-08-07 09:47:52,749     INFO   fetching base repo
2018-08-07 09:47:52,749    DEBUG   executing: git --work-tree /home/danghai/skt/skt-workdir --git-dir /home/danghai/skt/skt-workdir/.git -c user.name=skt -c user.email=skt fetch origin +a870a02cc963de35452bbed932560ed69725c4f2:refs/remotes/origin/a870a02cc963de35452bbed932560ed69725c4f2
2018-08-07 09:47:53,233     INFO   checking out a870a02cc963de35452bbed932560ed69725c4f2
2018-08-07 09:47:53,233    DEBUG   executing: git --work-tree /home/danghai/skt/skt-workdir --git-dir /home/danghai/skt/skt-workdir/.git -c user.name=skt -c user.email=skt checkout -q --detach refs/remotes/origin/a870a02cc963de35452bbed932560ed69725c4f2
2018-08-07 09:47:54,112    DEBUG   executing: git --work-tree /home/danghai/skt/skt-workdir --git-dir /home/danghai/skt/skt-workdir/.git -c user.name=skt -c user.email=skt reset --hard refs/remotes/origin/a870a02cc963de35452bbed932560ed69725c4f2
2018-08-07 09:47:55,053    DEBUG   git_commit: ['git', '--work-tree', '/home/danghai/skt/skt-workdir', '--git-dir', '/home/danghai/skt/skt-workdir/.git', 'show', '--format=%H', '-s']
2018-08-07 09:47:55,059     INFO   baserepo a870a02cc963de35452bbed932560ed69725c4f2: a870a02cc963de35452bbed932560ed69725c4f2
2018-08-07 09:47:55,059    DEBUG   git_commit_date: ['git', '--work-tree', '/home/danghai/skt/skt-workdir', '--git-dir', '/home/danghai/skt/skt-workdir/.git', 'show', '--format=%ct', '-s', 'a870a02cc963de35452bbed932560ed69725c4f2']
2018-08-07 09:47:55,066    DEBUG   state: basehead -> a870a02cc963de35452bbed932560ed69725c4f2
2018-08-07 09:47:55,066    DEBUG   state: commitdate -> 1520987126
2018-08-07 09:47:55,066    DEBUG   state: baserepo -> git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git
2018-08-07 09:47:55,072    DEBUG   state: mergerepo_00 -> git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git
2018-08-07 09:47:55,072    DEBUG   state: mergehead_00 -> a870a02cc963de35452bbed932560ed69725c4f2
2018-08-07 09:47:55,118    DEBUG   executing: git --work-tree /home/danghai/skt/skt-workdir --git-dir /home/danghai/skt/skt-workdir/.git -c user.name=skt -c user.email=skt remote add net-next git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git
Traceback (most recent call last):
  File "/usr/bin/skt", line 11, in <module>
    load_entry_point('skt', 'console_scripts', 'skt')()
  File "/home/danghai/skt/skt/executable.py", line 1028, in main
    args.func(cfg)
  File "/home/danghai/skt/skt/executable.py", line 168, in wrapper
    func(cfg)
  File "/home/danghai/skt/skt/executable.py", line 215, in cmd_merge
    (retcode, bhead) = ktree.merge_git_ref(*mb)
  File "/home/danghai/skt/skt/kerneltree.py", line 277, in merge_git_ref
    stderr=subprocess.PIPE)
  File "/home/danghai/skt/skt/kerneltree.py", line 110, in __git_cmd
    **kwargs)
  File "/home/danghai/skt/skt/kerneltree.py", line 93, in __git_cmd_call
    **kwargs
TypeError: check_output() got multiple values for keyword argument 'stderr'
```
