### ISSUE TITLE
Running `cleanup` with `--wipe` throw exception if no workdir is specified

### ISSUE THREAD

**Issue by veruu** [RH-FMK/skt#66]
Reproduce: just run `skt --state --wipe cleanup` (no steps before, don't have any rc or workdir)

```
Traceback (most recent call last):
  File "/usr/bin/skt", line 11, in <module>
    load_entry_point('skt', 'console_scripts', 'skt')()
  File "/home/vkabatova/git/skt/skt/executable.py", line 769, in main
    args.func(cfg)
  File "/home/vkabatova/git/skt/skt/executable.py", line 312, in cmd_cleanup
    shutil.rmtree(os.path.expanduser(cfg.get('workdir')))
  File "/usr/lib64/python2.7/posixpath.py", line 254, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

This should be easily solvable by checking if the workdir is specified before attempting to remove it (specifying a default to `.get()` won't help, just change the error to nonexistent file).

**Comment by veruu** [comment]
I should probably close this since the fix is merged...
