### ISSUE TITLE
Incomprehensible traceback on failure to submit a Beaker job

### ISSUE THREAD

**Issue by spbnick** [RH-FMK/skt#79]
Skt produces an exception with barely-related traceback when it fails to submit a Beaker job:

    + skt -vv --state --rc skt-rc --junit junit run --wait
    2018-04-18 13:17:58,346     INFO   runner type: beaker
    2018-04-18 13:17:58,346     INFO   beaker template: beakerjob.xml

    Configuration file not found. Please create an /etc/beaker/client.conf or ~/.beaker_client/config configuration file.
    2018-04-18 13:17:58,769     INFO   submitted jobid: None
    2018-04-18 13:17:58,776    ERROR   Exception caught: Traceback (most recent call last):
      File "/var/lib/jenkins/workspace/sktm@tmp/virtualenv/lib/python2.7/site-packages/skt/executable.py", line 102, in wrapper
        func(cfg)
      File "/var/lib/jenkins/workspace/sktm@tmp/virtualenv/lib/python2.7/site-packages/skt/executable.py", line 281, in cmd_run
        cfg.get('wait'), uid=cfg.get('uid'))
      File "/var/lib/jenkins/workspace/sktm@tmp/virtualenv/lib/python2.7/site-packages/skt/runner.py", line 433, in run
        self.wait(jobid, reschedule)
      File "/var/lib/jenkins/workspace/sktm@tmp/virtualenv/lib/python2.7/site-packages/skt/runner.py", line 369, in wait
        self.add_to_watchlist(jobid, reschedule)
      File "/var/lib/jenkins/workspace/sktm@tmp/virtualenv/lib/python2.7/site-packages/skt/runner.py", line 351, in add_to_watchlist
        root = self.getresultstree(jobid)
      File "/var/lib/jenkins/workspace/sktm@tmp/virtualenv/lib/python2.7/site-packages/skt/runner.py", line 115, in getresultstree
        bkr = subprocess.Popen(args, stdout=subprocess.PIPE)
      File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
        errread, errwrite)
      File "/usr/lib64/python2.7/subprocess.py", line 1025, in _execute_child
        raise child_exception
    TypeError: execv() arg 2 must contain only strings

Skt should handle the error, abort immediately, and produce a clear error message.

**Comment by veruu** [comment]
we should be handling infrastructure failures more gracefully now
